# Generated by Django 6.0.7 on 2026-07-28 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='سن')),
                ('field', models.CharField(choices=[('تجربی', 'تجربی'), ('ریاضی', 'ریاضی'), ('انسانی', 'انسانی')], default='تجربی', max_length=20, verbose_name='رشته تحصیلی')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره همراه والدین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
