# Generated by Django 6.0.7 on 2026-07-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='field',
            field=models.CharField(choices=[('تجربی', 'تجربی'), ('ریاضی', 'ریاضی'), ('انسانی', 'انسانی')], default='Experimental', max_length=20, verbose_name='Study Field'),
        ),
    ]
