# Generated by Django 6.0.7 on 2026-08-04 06:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'Friendship', 'verbose_name_plural': 'Friends'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/students/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL, verbose_name='Friend'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL, verbose_name='USER'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='field',
            field=models.CharField(choices=[('تجربی', 'تجربی'), ('ریاضی', 'ریاضی'), ('انسانی', 'انسانی')], default='تجربی', max_length=20, verbose_name='Study Field'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='سوابق و رزومه')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='consultants/', verbose_name='تصویر پروفایل')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس مشاور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Consultant Profile',
                'verbose_name_plural': 'Consultant Profiles',
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.consultantprofile', verbose_name='Selected Consultant'),
        ),
        migrations.CreateModel(
            name='ConsultantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز (۱ تا ۵)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر دانش\u200cآموز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.consultantprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultant Rating',
                'verbose_name_plural': 'Consultant Ratings',
                'unique_together': {('student', 'consultant')},
            },
        ),
    ]
