# Generated by Django 6.0.7 on 2026-08-04 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_friendship_options_studentprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='consultants/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='rezomeh'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='consultantrating',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name="Student's opinion"),
        ),
        migrations.AlterField(
            model_name='consultantrating',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score(1 to 5)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/students/', verbose_name='img'),
        ),
    ]
