# Generated by Django 6.0.7 on 2026-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_consultantprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Max Student Capacity'),
        ),
    ]
