# Generated by Django 6.0.7 on 2026-08-06 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studenttaskfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان برنامه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('file', models.FileField(upload_to='consultant_programs/', verbose_name='فایل برنامه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_programs', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_programs', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
