# Generated by Django 6.0.7 on 2026-07-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dark_color',
            field=models.CharField(default='text-indigo-400', max_length=50, verbose_name='Dark Mode Color Class'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon_name',
            field=models.CharField(default='BookOpen', max_length=50, verbose_name='Icon Name'),
        ),
        migrations.AddField(
            model_name='course',
            name='light_color',
            field=models.CharField(default='text-indigo-600', max_length=50, verbose_name='Light Mode Color Class'),
        ),
    ]
