# Generated by Django 6.0.7 on 2026-08-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_dark_color_course_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.CharField(choices=[('student', 'دانش\u200cآموز'), ('consultant', 'مشاور'), ('public', 'عمومی (همه)')], default='public', max_length=20, verbose_name='مخاطب دوره'),
        ),
    ]
