# Generated by Django 6.0.7 on 2026-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='target_audience',
            field=models.CharField(choices=[('student', 'دانش\u200cآموز'), ('consultant', 'مشاور'), ('public', 'عمومی')], default='public', max_length=20, verbose_name='Target Audience'),
        ),
    ]
