# Generated by Django 6.0.7 on 2026-07-28 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='نام درس')),
                ('topic', models.CharField(blank=True, max_length=150, verbose_name='مبحث')),
                ('start_time', models.TimeField(verbose_name='از ساعت')),
                ('end_time', models.TimeField(verbose_name='تا ساعت')),
                ('test_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تست')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='عنوان کار')),
                ('completed', models.BooleanField(default=False, verbose_name='وضعیت انجام')),
                ('date', models.DateField(verbose_name='تاریخ مربوط به کار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.TimeField(verbose_name='زمان خوابیدن')),
                ('wake_time', models.TimeField(verbose_name='زمان بیدار شدن')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
