# Generated by Django 6.0.7 on 2026-07-28 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysleeplog',
            options={'verbose_name': 'Daily Sleep Log', 'verbose_name_plural': 'Daily Sleep Logs'},
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'verbose_name': 'Study Session', 'verbose_name_plural': 'Study Sessions'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='dailysleeplog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dailysleeplog',
            name='sleep_time',
            field=models.TimeField(verbose_name='Sleep Time'),
        ),
        migrations.AlterField(
            model_name='dailysleeplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='dailysleeplog',
            name='wake_time',
            field=models.TimeField(verbose_name='Wake Time'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='test_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Test Count'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='topic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(verbose_name='Task Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Task Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
