# Generated by Django 6.0.7 on 2026-08-20 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_usersleepgroup_userstudygroup_usertaskgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysleeplog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
    ]
